"""add entities.duplicate_of

Revision ID: 6ef78da3bcee
Revises: 873566d3a418
Create Date: 2026-04-16 20:57:44.106344

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ef78da3bcee"
down_revision: str | Sequence[str] | None = "873566d3a418"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entities", sa.Column("duplicate_of", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_entities_duplicate_of"), "entities", ["duplicate_of"], unique=False)
    op.create_foreign_key(
        op.f("fk_entities_duplicate_of_entities"),
        "entities",
        "entities",
        ["duplicate_of"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_entities_duplicate_of_entities"), "entities", type_="foreignkey")
    op.drop_index(op.f("ix_entities_duplicate_of"), table_name="entities")
    op.drop_column("entities", "duplicate_of")
    # ### end Alembic commands ###
