"""initial schema: jobs entities raw_fetches sources exports blacklist

Revision ID: 98d128c81167
Revises:
Create Date: 2026-04-16 19:47:30.903591

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "98d128c81167"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blacklist",
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("domain", sa.String(length=255), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blacklist")),
        sa.UniqueConstraint("domain", name="uq_blacklist_domain"),
        sa.UniqueConstraint("email", name="uq_blacklist_email"),
    )
    op.create_index(op.f("ix_blacklist_domain"), "blacklist", ["domain"], unique=False)
    op.create_index(op.f("ix_blacklist_email"), "blacklist", ["email"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("query_raw", sa.Text(), nullable=False),
        sa.Column("query_validated", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("limit", sa.Integer(), nullable=False),
        sa.Column("budget_cap_usd", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_table(
        "sources",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("trust_score", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
        sa.UniqueConstraint("slug", name=op.f("uq_sources_slug")),
    )
    op.create_table(
        "entities",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=True),
        sa.Column("website", sa.Text(), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("phone", sa.String(length=64), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("city", sa.String(length=128), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("category", sa.String(length=128), nullable=True),
        sa.Column("socials", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("quality_score", sa.Integer(), nullable=True),
        sa.Column("review_status", sa.String(length=16), nullable=False),
        sa.Column("field_sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("external_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_entities_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entities")),
        sa.UniqueConstraint("job_id", "domain", name="uq_entity_job_domain"),
    )
    op.create_index(op.f("ix_entities_city"), "entities", ["city"], unique=False)
    op.create_index(op.f("ix_entities_country"), "entities", ["country"], unique=False)
    op.create_index(op.f("ix_entities_domain"), "entities", ["domain"], unique=False)
    op.create_index(op.f("ix_entities_email"), "entities", ["email"], unique=False)
    op.create_index(op.f("ix_entities_job_id"), "entities", ["job_id"], unique=False)
    op.create_index(op.f("ix_entities_quality_score"), "entities", ["quality_score"], unique=False)
    op.create_index(
        "ix_entity_external_ids_gin",
        "entities",
        ["external_ids"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "exports",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("format", sa.String(length=16), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_exports_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exports")),
    )
    op.create_index(op.f("ix_exports_job_id"), "exports", ["job_id"], unique=False)
    op.create_table(
        "raw_fetches",
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("source_slug", sa.String(length=64), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("method", sa.String(length=8), nullable=False),
        sa.Column("legal_basis", sa.String(length=64), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("bytes_fetched", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_raw_fetches_job_id_jobs"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_fetches")),
    )
    op.create_index(
        op.f("ix_raw_fetches_content_hash"), "raw_fetches", ["content_hash"], unique=False
    )
    op.create_index(op.f("ix_raw_fetches_job_id"), "raw_fetches", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_raw_fetches_source_slug"), "raw_fetches", ["source_slug"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_raw_fetches_source_slug"), table_name="raw_fetches")
    op.drop_index(op.f("ix_raw_fetches_job_id"), table_name="raw_fetches")
    op.drop_index(op.f("ix_raw_fetches_content_hash"), table_name="raw_fetches")
    op.drop_table("raw_fetches")
    op.drop_index(op.f("ix_exports_job_id"), table_name="exports")
    op.drop_table("exports")
    op.drop_index("ix_entity_external_ids_gin", table_name="entities", postgresql_using="gin")
    op.drop_index(op.f("ix_entities_quality_score"), table_name="entities")
    op.drop_index(op.f("ix_entities_job_id"), table_name="entities")
    op.drop_index(op.f("ix_entities_email"), table_name="entities")
    op.drop_index(op.f("ix_entities_domain"), table_name="entities")
    op.drop_index(op.f("ix_entities_country"), table_name="entities")
    op.drop_index(op.f("ix_entities_city"), table_name="entities")
    op.drop_table("entities")
    op.drop_table("sources")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_blacklist_email"), table_name="blacklist")
    op.drop_index(op.f("ix_blacklist_domain"), table_name="blacklist")
    op.drop_table("blacklist")
    # ### end Alembic commands ###
